### ISSUE TITLE
Crash while using Dragonborn Breath weapon

### ISSUE THREAD

**Issue by Tecohg** [DistantDig/digs-dnd-origins#26]
Im hosting an origins server, while testing some of the origins, i noticed that the dragonborn origin causes a crash as soon as we use the breath ability.

**Comment by DistantDig** [comment]
interesting, what version is this on?

**Comment by Anhelm** [comment]
version 1.20 same problem

**Comment by Anhelm** [comment]
https://pastebin.com/BvayqDmA

**Comment by LReaper31** [comment]
Hi, same issue than Anhelm.

I'm uploading the crash log in hope it can help you : [https://pastebin.com/d2ZpUGdk](url)

regards

**Comment by YumatanGames** [comment]
Hey, I'm experiencing the same issue. Here's the crashlog, hope it helps:
https://pastebin.com/f7P01Ght

**Comment by DistantDig** [comment]
Thank you all for the feedback! This issue should now be fixed in 0.0.11
